export const routePaths = {
    home: '/',
    maps:"/maps",
    userLogin:"/userLogin",
    adminLogin:"/adminLogin",
    adminRegistration:"/adminRegistration",
    driverLogin:"/driverLogin",
    location:"/location",
    profile:"/profile",
    adminprofile:"/adminprofile",
    addLocations:"/addLocations",
    bookingconfirmation:"bookingconfirmation",
    bookingsucess:"bookingsucess",
    quatations:"quatationsuccess",
    driverProfile:"/driverProfile",
    signIn: '/sign-in',
    settings: '/settings',
    userRegistration: '/userRegistration',
    driverRegistration: '/driverRegistration',
    verifyEmail: '/verify-email',
    userprofile: "/user-profile",
    authentication: {
        index: "/authentication",
        signIn: "/authentication/sign-in",
        newPassword: "/authentication/new-password",
    },
};
