export const routePaths = {
    home: "/",
    maps: "/maps",
    userLogin: "/user-login",
    userRegistration: "/user-registration",
    adminLogin: "/adminLogin",
    adminRegistration: "/adminRegistration",
    driverLogin: "/driverLogin",
    location: "/location",
    profile: "/profile",
    adminprofile: "/adminprofile",
    addLocations: "/addLocations",
    bookingconfirmation: "bookingconfirmation",
    bookingsucess: "bookingsucess",
    driverProfile: "/driverProfile",
    signIn: "/sign-in",
    settings: "/settings",
    driverRegistration: "/driverRegistration",
    verifyEmail: "/verify-email",
    authentication: {
        index: "/authentication",
        signIn: "/authentication/sign-in",
        newPassword: "/authentication/new-password",
    },
};
